---
version: "3"

env:
  PY_PM: poetry
  PY_RUNNER: poetry run
  PYTESTARGS: -vvl --workers auto
  BLACKARGS: --line-length 128 --check --diff

tasks:
  default:
    cmds:
      - task -l

  #############################################################################
  #
  # Environment Setup
  #
  #############################################################################
  setup:
    desc: Setup environment
    cmds:
      - task: setup-python-env
      - task: setup-pre-commit

  setup-python-env:
    desc: Setup Python environment
    cmds:
      - $PY_PM update

  setup-pre-commit:
    desc: Setup Pre-Commit environment
    cmds:
      - $PY_RUNNER pre-commit autoupdate
      - $PY_RUNNER pre-commit install
      - $PY_RUNNER pre-commit install --install-hooks
      - $PY_RUNNER pre-commit install --hook-type commit-msg
      - $PY_RUNNER pre-commit install --hook-type pre-push

  #############################################################################
  #
  # Release management
  #
  #############################################################################
  release:
    desc: Release MINOR version bump
    cmds:
      - $PY_RUNNER cz bump --check-consistency --increment MINOR --no-verify

  release-major:
    desc: Release MAJOR version bump
    cmds:
      - $PY_RUNNER cz bump --check-consistency --increment MAJOR --no-verify

  release-patch:
    desc: Release PATCH version bump
    cmds:
      - $PY_RUNNER cz bump --check-consistency --increment PATCH --no-verify

  publish:
    desc: Push to remote
    cmds:
      - git push -v --progress
      - git push -v --progress --tags

  #############################################################################
  #
  # Checking and Linting
  #
  #############################################################################
  check:
    desc: Run pre-commit
    deps:
      - lint
  lint:
    desc: Run pre-commit
    deps:
      - linting
  linting:
    desc: Run pre-commit
    deps:
      - pre-commit

  pre-commit:
    desc: Run pre-commit
    cmds:
      - $PY_RUNNER pre-commit run --all-files

  test:
    desc: Run pytest
    deps:
      - pytest

  pytest:
    desc: Run pytest
    cmds:
      - $PY_RUNNER pytest $PYTESTARGS tests

  #############################################################################
  #
  # Cookie options
  #
  #############################################################################
  cookie-updater:
    desc: Update all cookies
    cmds:
      - pushd *cookiecutter.github_repo*; pre-commit autoupdate; popd
      - pushd *cookiecutter.github_repo*/cookiecutter.github_repo; pre-commit autoupdate; popd

  #############################################################################
  #
  # Custom options
  #
  #############################################################################
  clean:
    desc: Clean up
    cmds:
      - rm -rvf tmp
      - git clean -fdx
