---
version: "3"

env:
  # TF_AUTOAPPROVE: -auto-approve
  TF_AUTOAPPROVE:

tasks:
  default:
    cmds:
      - task -l

  ################################################################################
  #
  # Terraform
  #
  ################################################################################
  init:
    desc: "Initialize Terraform"
    cmds:
      - terraform init -upgrade

  plan:
    desc: "Plan the changes"
    cmds:
      - terraform plan

  apply:
    desc: "Apply Terraform changes"
    cmds:
      - terraform apply $TF_AUTOAPPROVE

  output:
    desc: "Show Terraform output"
    cmds:
      - terraform output

  destroy:
    desc: "Destroy Terraform state"
    cmds:
      - terraform destroy $TF_AUTOAPPROVE
